build:
  environment:
    php: '8.3'
    mysql: true

  dependencies:
    override:
      - composer install --no-interaction --prefer-dist

  tests:
    override:
      - command: cp .env.example .env
      - command: php artisan key:generate
      - command: mysql -u root -e "CREATE DATABASE IF NOT EXISTS \`swinn-test\`;"
      - command: php artisan migrate --force
      - command: php artisan passport:install --no-interaction
      - command: vendor/bin/phpunit
        coverage:
          file: build/logs/clover.xml
          format: clover
        environment:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: swinn-test
          DB_USERNAME: root
          DB_PASSWORD: ''

checks:
  php:
    code_rating: true
    duplication: true